spring:
    datasource:
       driver-class-name: org.postgresql.Driver
       url: ${DB_URL}
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true

