spring:
    datasource:
       driver-class-name: org.postgresql.Driver
       url: ${DB_URL}g
       username: ${DB_USER}
       password: ${DB_PASSWORD}
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: update
        properties:
            hibernate:
                format_sql: 'true'
        show-sql: 'true'

